name: Download File

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps: 
    - name: |
        Project=XayahSuSuSu/Android-DataBackup
        tag=$(wget -qO- -t1 -T2 "https://api.github.com/repos/${Project}/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
        curl -O https://github.com/${Project}/releases/download/${tag}/DataBAckup-${tag}.apk
      run: |
        Project=XayahSuSuSu/Android-DataBackup
        tag=$(wget -qO- -t1 -T2 "https://api.github.com/repos/${Project}/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
        curl -O https://github.com/${Project}/releases/download/${tag}/DataBAckup-${tag}.apk


    - name: Organize files
      id: organize
      run: |
        echo "FILE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
        
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::file_transfer_v$(date +"%m.%d-%H%M")"
        touch release.txt
        echo "There is nothing..." >> release.txt
        echo "::set-output name=status::success"

    - name: Upload file to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FILE }}/*
        
        
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
